-- Preserve column types, nullability, and the existing general_ci comparison rules.
-- MySQL DDL commits implicitly. Keep utf8mb4 when rolling back application code.

ALTER TABLE `user`
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `social_id` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `email` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE profile
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `first_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `last_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `image_url` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE website
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `domain` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `favicon_url` VARCHAR(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE website_category_classification_outbox
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `last_error_message` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE page
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `url` VARCHAR(768) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `title` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE user_excluded_website_domain
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `domain` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE recap
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `summary` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE recap_section
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE recap_timeline
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE recap_topic
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `keyword` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE BATCH_JOB_INSTANCE
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `JOB_NAME` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `JOB_KEY` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE BATCH_JOB_EXECUTION
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `STATUS` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `EXIT_CODE` VARCHAR(2500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `EXIT_MESSAGE` VARCHAR(2500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `PARAMETER_NAME` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `PARAMETER_TYPE` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `PARAMETER_VALUE` VARCHAR(2500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `IDENTIFYING` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE BATCH_STEP_EXECUTION
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `STEP_NAME` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `STATUS` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `EXIT_CODE` VARCHAR(2500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `EXIT_MESSAGE` VARCHAR(2500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `SHORT_CONTEXT` VARCHAR(2500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `SERIALIZED_CONTEXT` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `SHORT_CONTEXT` VARCHAR(2500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    MODIFY COLUMN `SERIALIZED_CONTEXT` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE BATCH_STEP_EXECUTION_SEQ
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `UNIQUE_KEY` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE BATCH_JOB_EXECUTION_SEQ
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `UNIQUE_KEY` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE BATCH_JOB_SEQ
    DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    MODIFY COLUMN `UNIQUE_KEY` CHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;
