spring:
  application:
    name: retoday-batch
  main:
    banner-mode: off
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true
  profiles:
    include:
    - auth
    - db
    - ai
recap:
  ai-provider: ${RECAP_AI_PROVIDER:GEMINI}
logging:
  config: classpath:log4j2-${spring.profiles.active}.yaml
---
spring:
  config:
    activate:
      on-profile: local
management:
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: false
---
spring:
  config:
    activate:
      on-profile:
      - dev
      - prod
management:
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          address: ${PROMETHEUS_PUSHGATEWAY_ADDRESS}
          format: text
          push-rate: 1m
          job: ${spring.application.name}
          shutdown-operation: put
          grouping-key:
            environment: ${spring.profiles.active}
            cronjob: ${BATCH_CRONJOB_NAME}
