spring:
  application:
    name: retoday-batch
  main:
    banner-mode: off
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true
  profiles:
    include:
    - auth
    - db
    - ai
server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
        add-additional-paths: true
    prometheus:
      access: read_only
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
logging:
  config: classpath:log4j2-${spring.profiles.active}.yaml
---
spring:
  config:
    activate:
      on-profile: local
management:
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: false
---
spring:
  config:
    activate:
      on-profile:
      - dev
      - prod
management:
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          address: ${PROMETHEUS_PUSHGATEWAY_ADDRESS}
          format: text
          push-rate: 1m
          job: ${spring.application.name}
          shutdown-operation: put
          grouping-key:
            environment: ${spring.profiles.active}
            cronjob: ${BATCH_CRONJOB_NAME}
