spring:
  application:
    name: retoday-batch
  main:
    banner-mode: off
    web-application-type: none
  config:
    import:
    - classpath:application-core.yaml
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true
logging:
  config: classpath:log4j2-${spring.profiles.active}.yaml
---
spring:
  config:
    activate:
      on-profile: local
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: false
---
spring:
  config:
    activate:
      on-profile:
      - dev
      - prod
management:
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          address: ${PROMETHEUS_PUSHGATEWAY_ADDRESS}
          format: text
          push-rate: 1m
          job: ${spring.application.name}
          shutdown-operation: put
          grouping-key:
            environment: ${spring.profiles.active}
            cronjob: ${CRON_JOB_NAME}
