name: Deploy
on:
  push:
    branches:
    - dev
    - prod
  workflow_dispatch:
jobs:
  deploy-images:
    name: Deploy images
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    outputs:
      api-image: ${{ steps.deploy-images.outputs.api-image }}
      batch-image: ${{ steps.deploy-images.outputs.batch-image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 21
        cache: gradle
    - name: Run tests
      run: ./gradlew test
    - name: Deploy images to container registry
      id: deploy-images
      env:
        API_IMAGE: ${{ vars.API_IMAGE_NAME }}:${{ github.sha }}
        BATCH_IMAGE: ${{ vars.BATCH_IMAGE_NAME }}:${{ github.sha }}
      run: |
        ./gradlew :api:jib \
          -Djib.to.image=${{ env.API_IMAGE }} \
          -Djib.to.auth.username=${{ secrets.GABIA_USERNAME }} \
          -Djib.to.auth.password=${{ secrets.GABIA_PASSWORD }}

        ./gradlew :batch:jib \
          -Djib.to.image=${{ env.BATCH_IMAGE }} \
          -Djib.to.auth.username=${{ secrets.GABIA_USERNAME }} \
          -Djib.to.auth.password=${{ secrets.GABIA_PASSWORD }}

        echo "api-image=$API_IMAGE" >> "$GITHUB_OUTPUT"
        echo "batch-image=$BATCH_IMAGE" >> "$GITHUB_OUTPUT"
  update-chart:
    name: Update chart
    runs-on: ubuntu-latest
    needs: deploy-images
    environment: ${{ github.ref_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ vars.CHART_REPOSITORY }}
        token: ${{ secrets.CHART_REPOSITORY_TOKEN }}
    - name: Update images
      env:
        API_IMAGE: ${{ needs.deploy-images.outputs.api-image }}
        BATCH_IMAGE: ${{ needs.deploy-images.outputs.batch-image }}
      run: |
        yq -i '.api.image = strenv(API_IMAGE)' ./application/values-${{ github.ref_name }}.yaml
        yq -i '.batch.image = strenv(BATCH_IMAGE)' ./application/values-${{ github.ref_name }}.yaml
    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git diff --cached --quiet || \
        git commit \
          -m "chore: update image tag to ${GITHUB_SHA::7}" \
          -m "https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
        git push
  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs:
    - deploy-images
    - update-chart
    if: always()
    steps:
    - name: Notify discord
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
        title: "[${{ github.ref_name }}] Deploy"
        description: |
          ${{ contains(needs.*.result, 'failure') && '배포 중 오류가 발생했습니다.' || '성공적으로 이미지를 배포하고 Helm 차트에 반영했습니다.' }}

          **Branch:** `${{ github.ref_name }}`
          **Commit:** `${{ github.sha }}`
          **Actor:** ${{ github.actor }}
        color: ${{ contains(needs.*.result, 'failure') && '0xED4245' || '0x57F287' }}
